import random

countries = ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Republic of the Congo", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czechia", "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "The Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States of America", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"]
currencies = ['Afghani', 'Lek', 'Algerian Dinar', 'Euro', 'Kwanza', 'East Caribbean Dollar', 'Argentine Peso', 'Armenian Dram', 'Australian Dollar', 'Euro', 'Azerbaijanian Manat', 'Bahamian Dollar', 'Bahraini Dinar', 'Taka', 'Barbados Dollar', 'Belarusian Ruble', 'Euro', 'Belize Dollar', 'CFA Franc', 'Ngultrum', 'Boliviano', 'Convertible Mark', 'Pula', 'Brazilian Real', 'Brunei Dollar', 'Bulgarian Lev', 'CFA Franc', 'Burundi Franc', 'Cabo Verde Escudo', 'Riel', 'CFA Franc', 'Canadian Dollar', 'CFA Franc', 'CFA Franc', 'Chilean Peso', 'Yuan Renminbi', 'Colombian Peso', 'Comoro Franc', 'CFA Franc', 'Costa Rican Colon', 'CFA Franc', 'Croatian Kuna', 'Cuban Peso', 'Euro', 'Czech Koruna', 'Congolese Franc', 'Danish Krone', 'Djibouti Franc', 'East Caribbean Dollar', 'Dominican Peso', 'US Dollar', 'Egyptian Pound', 'US Dollar', 'CFA Franc', 'Nakfa', 'Euro', 'Lilangeni', 'Ethiopian Birr', 'Fiji Dollar', 'Euro', 'Euro', 'CFA Franc', 'Dalasi', 'Lari', 'Euro', 'Ghana Cedi', 'Euro', 'East Caribbean Dollar', 'Quetzal', 'Guinea Franc', 'CFA Franc', 'Guyana Dollar', 'Gourde', 'Lempira', 'Forint', 'Iceland Krona', 'Indian Rupee', 'Rupiah', 'Iranian Rial', 'Iraqi Dinar', 'Euro', 'New Israeli Shekel', 'Euro', 'Jamaican Dollar', 'Yen', 'Jordinian Dollar', 'Tenge', 'Kenyan Shilling', 'Australian Dollar', 'Euro', 'Kuwaiti Dinar', 'Som', 'Kip', 'Euro', 'Lebanese Pound', 'Loti', 'Liberian Dollar', 'Libyan Dinar', 'Swiss Franc', 'Euro', 'Euro', 'Malagasy Ariary', 'Malawi Kwacha', 'Malaysian Ringgit', 'Rufiyaa', 'CFA Franc', 'Euro', 'US Dollar', 'Ouguiya', 'Mauritius Rupee', 'Mexican Peso', 'US Dollar', 'Moldovan Leu', 'Euro', 'Tugrik', 'Euro', 'Moroccan Dirham', 'Metical', 'Kyat', 'Namibian Dollar', 'Australian Dollar', 'Nepalese Rupee', 'Euro', 'New Zealand Dollar', 'Corodoba Oro', 'CFA Franc', 'Naira', 'Won', 'Denar', 'Norwegian Krone', 'Rial Omani', 'Pakistan Rupee', 'US Dollar', 'New Israeli Shekel', 'Balboa', 'Kina', 'Guarani', 'Sol', 'Philippine Peso', 'Zloty', 'Euro', 'Qatari Rial', 'Romanian Leu', 'Russian Ruble', 'Rwanda Franc', 'East Caribbean Dollar', 'East Caribbean Dollar', 'East Caribbean Dollar', 'Tala', 'Euro', 'Dobra', 'Saudi Riyal', 'CFA Franc', 'Serbian Dinar', 'Seychelles Rupee', 'Leone', 'Singapore Dollar', 'Euro', 'Euro', 'Solomon Islands Dollar', 'Somali Shilling', 'Rand', 'Won', 'South Sudanese Pound', 'Euro', 'Sri Lanka Rupee', 'Sudanese Pound', 'Suriname Dollar', 'Swedish Krona', 'Swiss Franc', 'Syrian Pound', 'New Taiwan Dollar', 'Somoni', 'Tanzanian Shilling', 'Baht', 'US Dollar', 'CFA Franc', "Pa'anga", 'Trinidad and Tobago Dollar', 'Tunisian Dinar', 'Turkish Lira', 'Turkmenistan New Manat', 'Australian Dollar', 'Ugandan Shilling', 'Hryvnia', 'UAE Dirham', 'Pound Sterling', 'US Dollar', 'Peso Uruguayo', 'Uzbekistan Sum', 'Vatu', 'Boliviar', 'Dong', 'Yemeni Rial', 'Zambian Kwacha', 'Zimbabwe Dollar']

while len(countries) > 0:
    i = random.randint(0, len(countries)-1)
    a = input(f"{countries[i]}: ").upper()

    if a == currencies[i].upper():
        print("YAY!")
    else:
        print(currencies[i])

    countries.pop(i)
    currencies.pop(i)